# Generated by Django 3.2.23 on 2024-02-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasklist2',
        ),
    ]
